filepath:
  raw_data:
    directory: data/raw/
    files:
      file_a: # TODO
  processed_data:
    directory: data/processed/
    files: # TODO
  model_output:
    directory: model/
    files:

# tuple with >=3 elements: discrete range
# tuple with 2 elements: continuous range
# list: choices
model:
  xgboost:
    n_jobs: 1
    random_state: 42
    n_estimators: ["integer", [1, 2000, 1]]
    learning_rate: ["discrete", [0.01, 0.3, 0.01]]
    max_depth: ["integer", [6, 18, 2]]
    gamma: ["uniform", [0, 9]]
    reg_alpha: ["integer", [0, 180, 1]]
    reg_lambda: ["uniform", [0, 10]]
    subsample: ["uniform", [0.5, 1]]
    min_child_weight: ["quniform", [0, 10, 1]]
    colsample_bytree: ["uniform", [0.5, 1]]